name: kelime_oyunu
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4
  cloud_firestore: ^4.17.5 # güncel sürüm

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/data/words_easy.json
    - assets/data/words_medium.json
    - assets/data/words_hard.json
